language: android

android:
  components:
    - build-tools-25.0.2
    - android-25
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

install: ./gradlew copyTestAssets test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)